USE PanelesSolares_ELGG;
GO
SELECT * FROM sys.certificates;
GO
CREATE DATABASE ENCRYPTION KEY WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE certPaneles;
GO
ALTER DATABASE PanelesSolares_ELGG SET ENCRYPTION = ON;
GO
